//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estacionamiento_Forms.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Este programa lo hice:
* Un domingo a la tarde en cuarentena
* Tomando té de vainilla (se los super recomiendo)
* Escuchando una lista de Queen en spotify (se me pegó la version de  Tie Your Mother Down  del Live Rock Montreal de YouTube).

Aun así, no esperen mucho de este programita!
Funciona,pero se puede mejorar mucho. Estaria bueno que lo mejores con el correr de las clases.

Os vereis.")]
        public string HiddenMessage {
            get {
                return ((string)(this["HiddenMessage"]));
            }
            set {
                this["HiddenMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Este programirijillo mocho que hice,que no esta tannn mal... :P")]
        public string HiddenMessage2 {
            get {
                return ((string)(this["HiddenMessage2"]));
            }
            set {
                this["HiddenMessage2"] = value;
            }
        }
    }
}
